# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - laundry-api-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc python3-dev libffi-dev

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install --no-build-isolation pydantic==2.5.0 pydantic-core==2.14.1
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_720F8F266495476A98F659F7249D1999 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FD8B8811D50647BDAB068F74E2E86B09 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1DBF40DDB4AF4F39B337BDA4B1B2CEB3 }}

      - name: Configure App Service Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: laundry-api-server
          mask-inputs: false
          general-settings: '{"linuxFxVersion": "PYTHON|3.11"}'
          app-settings: '{"WEBSITE_RUN_FROM_PACKAGE": "1", "SCM_DO_BUILD_DURING_DEPLOYMENT": "true", "ENABLE_ORYX_BUILD": "true"}'
                "name": "PYTHON_VERSION",
                "value": "3.11"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "true"
              },
              {
                "name": "ENABLE_ORYX_BUILD",
                "value": "true"
              }
            ]

      - name: Configure App Service Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'laundry-api-server'
          app-settings-json: '[
            {
              "name": "PYTHON_VERSION",
              "value": "3.11"
            },
            {
              "name": "ENABLE_ORYX_BUILD",
              "value": "true"
            },
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true"
            },
            {
              "name": "WEBSITE_RUN_FROM_PACKAGE",
              "value": "1"
            }
          ]'

      - name: Configure App Service Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: laundry-api-server
          mask-inputs: false
          settings: |
            [
              {
                "name": "PYTHON_VERSION",
                "value": "3.11"
              },
              {
                "name": "ENABLE_ORYX_BUILD",
                "value": "true"
              },
              {
                "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                "value": "true"
              },
              {
                "name": "WEBSITE_RUN_FROM_PACKAGE",
                "value": "1"
              }
            ]

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'laundry-api-server'
          slot-name: 'Production'
          package: '.'
          clean: true
          restart: true
          startup-command: 'python3.11 -m gunicorn app.main:app --host 0.0.0.0'
          